### PR TITLE
[Event Manager PR#3] Metalanguage rule executor for java execution engine

### PR DESCRIPTION
**Pull request by d-leroy**
## Description

Use the extension points provided by `org.eclipse.gemoc.executionframework.event.manager` to contribute the `K3RuleExecutor`, which allows to call exposed execution rules from K3-based operational semantics.

## Changes

 Add `K3RuleExecutor`, contributed through the `org.eclipse.gemoc.executionframework.event.metalanguage_rule_executor` extension point.

### CODE REVIEW

**Comment by ebousse** [comment]
Enabled the CI here: https://ci.eclipse.org/gemoc/job/gemoc-studio-integration/job/metalanguage-integration-facade/

**Comment by ebousse** [comment]
We have a build error:
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.gemoc.gemoc_studio.headless 3.3.0.qualifier
[ERROR]   Missing requirement: org.eclipse.gemoc.execution.sequential.javaengine 4.0.0.qualifier requires 'osgi.bundle; org.eclipse.gemoc.executionframework.event.manager 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.gemoc.gemoc_studio.headless 3.3.0.qualifier depends on: osgi.bundle; org.eclipse.gemoc.execution.sequential.javaengine 0.0.0
```

@dvojtise @d-leroy Any idea? It seems the event manager plugin canno be found, but it's strange since it should me part of `master` now.

**Comment by dvojtise** [comment]
apparently      is not compîled by the CI in master (not in the list of compiled modules): cf https://github.com/eclipse/gemoc-studio-modeldebugging/blob/6f79e8103687669ddb830d245b2792a9921e8e14/framework/execution_framework/plugins/pom.xml#L21

**Comment by ebousse** [comment]
I found the problem: the previous PR on _gemoc-studio-modeldebugging_ (https://github.com/eclipse/gemoc-studio-modeldebugging/pull/187) was not correct, because the new event manager module was not added to the corresponding `pom.xml` file. I've opened a PR with a fix here: https://github.com/eclipse/gemoc-studio-modeldebugging/pull/189

**Comment by ebousse** [comment]
> apparently `org.eclipse.gemoc.executionframework.event.manager` is not compiled by the CI in master (not in the list of compiled modules): cf https://github.com/eclipse/gemoc-studio-modeldebugging/blob/6f79e8103687669ddb830d245b2792a9921e8e14/framework/execution_framework/plugins/pom.xml#L21

Looks like we made the same discovery at the same time 😄

**Comment by ebousse** [comment]
With https://github.com/eclipse/gemoc-studio-modeldebugging/pull/189 merged on `gemoc-studio-modeldebugging`, we now have a successful build! Let's merge.

**Pull request merged**
